---
title: "TBIJYemen"
author: "Soo Wan Kim"
date: "May 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(scales)
library(lubridate)
library(maptools)
library(raster)
library(rgdal)
library(broom)
library(modelr)
library(knitr)
library(xtable)
library(coefplot)

theme_set(theme_minimal())

#saved xlsx file as csv in Excel
gtd <- read_csv("Data/Terrorism Data/globalterrorismdb_0616dist.csv")

gtd_filt <- gtd %>%
  mutate(TargetType = ifelse(targtype1_txt %in% c("Military", "Police", "Terrorists/Non-State Militia"),
"Military", 
ifelse(targtype1_txt %in% c("Government (Diplomatic)", "Government (General)", "Violent Political Party"),
       "Government", "Other"))) %>%
  mutate(WeaponType = ifelse(weaptype1_txt %in% c("Biological", "Chemical", "Radiological",
                                                  "Fake Weapons", "Sabotage Equipment",
                                                         "Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)", "Other", "Unknown"), "Unknown/Other",
                                    ifelse(weaptype1_txt == "Explosives/Bombs/Dynamite", 
                                           "Explosives", weaptype1_txt)))

#set beginning of time range
y <- 2012
y_txt <- "2012"
```

# Yemen

## Descriptive statistics

### Terrorist attacks

```{r terrorist attack data}
gtd_yemen <- gtd_filt %>%
  filter(country_txt == "Yemen" & iyear >= y & guncertain1 == 0 & gname %in% 
           c("Al-Qaida in the Arabian Peninsula (AQAP)", "Al-Qaida in Yemen")) %>%
  mutate(date = paste0(iyear,"-",imonth,"-",iday)) %>%
  transform(date = as.Date(date, "%Y-%m-%d")) %>%
  arrange(date)
```

#### Graphs

```{r number of attacks by year}
count_year <- gtd_yemen %>%
  group_by(iyear) %>%
  summarize(count = n())

ggplot(count_year, aes(iyear, count)) + 
  geom_line(linetype = 2) + 
  geom_point() + 
  labs(title = "Number of confirmed attacks by AQAP and affiliates, by year",
       x = "Year", y = "Number of attacks") + 
  theme(panel.grid.minor = element_blank())
```


```{r intervals between attacks}
gtd_yemen_casualties <- gtd_yemen %>%
  group_by(date) %>%
  summarize(attack_fatalities = sum(nkill))

date <- as.character(gtd_yemen_casualties$date)
date2 <- c(date, NA)
date2 <- date2[-1]
gtd_yemen_casualties$date2 <- as.Date(date2, "%Y-%m-%d")

gtd_yemen_casualties <- gtd_yemen_casualties %>%
  mutate(lull = date2 - date)

#histogram
ggplot(gtd_yemen_casualties, aes(log(as.numeric(lull) + 1))) + 
  geom_histogram(bins = 90)

#scatter plot over time
ggplot(gtd_yemen_casualties, aes(date, log(as.numeric(lull)+1))) + 
  geom_point(alpha = 0.3) + 
  geom_line(size = 0.3) + 
  geom_smooth() +
  labs(title = "Intervals between AQAP attacks in Yemen, logged",
       x = "Date", y = "Intervals (log)")
```

```{r attack location frequency map}
yemen<-getData("GADM", country="YE", level=1)

yemen1 <-spTransform(yemen, CRS("+init=EPSG:2089"))

provinces <- unique(gtd_yemen$provstate)

gtd_yemen_map <- gtd_yemen %>%
  transform(provstate = ifelse(provstate == "Unknown", NA, provstate)) %>%
  transform(provstate = ifelse(provstate == "Adan", "`Adan", provstate)) %>%
  transform(provstate = ifelse(provstate == "Ad Dali", "Al Dali'", provstate)) %>%
  transform(provstate = ifelse(provstate == "Taizz", "Ta`izz", provstate)) %>%
  transform(provstate = ifelse(provstate == "Saada", "Sa`dah", provstate)) %>%
  transform(provstate = ifelse(provstate == "Sanaa", "San`a", provstate)) %>%
  transform(provstate = ifelse(provstate == "Marib", "Ma'rib", provstate)) 

#yemen1@data$NAME_1

NAME_1 <- yemen1@data$NAME_1

count_all <- gtd_yemen_map %>%
  group_by(provstate) %>%
  summarize(count = n()) %>%
  rename(`NAME_1` = provstate)

yemen1@data$id <- rownames(yemen1@data)
yemen1@data <- left_join(yemen1@data, count_all, by = "NAME_1")
yemen1_df <- fortify(yemen1)
yemen1_df <- left_join(yemen1_df, yemen1@data, by = "id")

theme_opts<-list(theme(panel.grid.minor = element_blank(),
                       panel.grid.major = element_blank(),
                       panel.background = element_blank(),
                       plot.background = element_blank(),
                       axis.line = element_blank(),
                       axis.text.x = element_blank(),
                       axis.text.y = element_blank(),
                       axis.ticks = element_blank(),
                       axis.title.x = element_blank(),
                       axis.title.y = element_blank()))

ggplot() + 
  geom_polygon(data = yemen1_df, aes(x = long, y = lat, group = group, fill =
                                       count), color = "black", size = 0.25) +
  theme(aspect.ratio=.7) + 
  labs(title = "Confirmed terrorist attacks by AQAP and affiliates, 2011 - 2015",
       fill = "Frequency") + 
  scale_fill_gradient(low='#FFFFCC', high='#006837') + 
  theme_opts
```

```{r attacks target type}
targ_count <- gtd_yemen %>%
  group_by(iyear, TargetType) %>%
  summarize(freq = n()) %>%
  mutate(freq_weight = freq/sum(freq)) %>%
  transform(TargetType = as.factor(TargetType)) %>%
  transform(TargetType = factor(TargetType, levels = c("Other", "Government", "Military")))

ggplot(targ_count, aes(iyear, freq_weight)) + 
  geom_bar(aes(fill = TargetType), stat = "identity") + 
  labs(title = "Percentage of attacks by target type",
       x = "Year", y = "Percentage of attacks",
       fill = "Target Type") + 
  scale_y_continuous(labels = percent_format()) + 
  theme(panel.grid.minor = element_blank())
```

```{r attacks weapon type}
weap_count <- gtd_yemen %>%
  group_by(iyear, WeaponType) %>%
  summarize(freq = n()) %>%
  mutate(freq_weight = freq/sum(freq)) %>%
  transform(WeaponType = as.factor(WeaponType)) %>%
  transform(WeaponType = factor(WeaponType, 
                                levels = c("Unknown/Other", "Incendiary", "Melee",
                                           "Firearms", "Explosives")))

ggplot(weap_count, aes(iyear, freq_weight)) + 
  geom_bar(aes(fill = WeaponType), stat = "identity") + 
  labs(title = "Percentage of attacks by weapon type",
       x = "Year", y = "Percentage of attacks",
       fill = "Weapon Type") + 
  scale_y_continuous(labels = percent_format())
```
```{r attacks suicide}
sui_count <- gtd_yemen %>%
  group_by(iyear, suicide) %>%
  summarize(freq = n()) %>%
  mutate(freq_weight = freq/sum(freq)) %>%
  transform(suicide = as.factor(suicide)) %>%
  mutate(suicide_label = ifelse(suicide == 0, "No", ifelse(suicide == 1, "Yes", NA)))

ggplot(sui_count, aes(iyear, freq_weight)) + 
  geom_bar(aes(fill = suicide_label), stat = "identity") + 
  labs(title = "Use of suicide attacks over time",
       x = "Year", y = "Percentage of attacks", fill = "Suicide\nattack?") + 
  scale_y_continuous(labels = percent_format())
```

#### Table

```{r attacks table}
options(xtable.floating = FALSE)
options(xtable.timestamp = "")

#headings
colnames <- c("Year", "# Attacks", "Avg. Interval (Days)", "Interval range (Days)")

#year
year <- c(2011, 2012, 2013, 2014, 2015, "Total")
#number of attacks
attacks <- c(count_year$count, sum(count_year$count))

lull <- gtd_yemen_casualties %>%
  mutate(year = year(date)) %>%
  group_by(year) %>%
  summarize(avg = round(mean(as.numeric(lull), na.rm = TRUE),1), 
            min = min(as.numeric(lull), na.rm = TRUE), 
            max = max(as.numeric(lull), na.rm = TRUE))
lull_total <- c(round(mean(gtd_yemen_casualties$lull, na.rm = TRUE),1),
                min(gtd_yemen_casualties$lull, na.rm = TRUE),
                max(gtd_yemen_casualties$lull, na.rm = TRUE))
avg_interval <- c(lull$avg, as.numeric(lull_total[1]))
min_interval <- c(lull$min, as.numeric(lull_total[2]))
max_interval <- c(lull$max, as.numeric(lull_total[3]))
interval_range <- data.frame(min_interval, max_interval) %>%
  unite(interval_range, min_interval, max_interval, sep = ", ")

attack_table <- data.frame(year, attacks, avg_interval, interval_range)
colnames(attack_table) <- colnames
xtable(attack_table)
```


### Covert strikes

```{r}
TBIJYemen <- read_csv("Data/Strikes Data/Tidy data/TBIJYemenTidy.csv") %>%
  transform(Date = as.Date(Date, "%Y-%m-%d")) %>%
  transform(Province = ifelse(Province %in% c("Hadhramout", "Hadramout", "Hadaramout"), 
                              "Hadramawt", 
                              ifelse(Province %in% c("Across Yemen", "Southern Yemen", "Between Marib and Shabwa", "Shabwa/Hadramout", "Shabwa/Mareb border", "Jawf-Mareb border", "Bayda-Shabwa border", "Central Yemen", "-", "Marib/Al Jawf", "Across central Yemen", "Yemen", "Multiple provinces"), NA, Province)))
TBIJYemen$Province <- gsub("Sanaa", "San`a", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Shabwa", "Shabwah", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Saada", "Sa`dah", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Marib", "Ma'rib", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Mareb", "Ma'rib", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Jawf", "Al Jawf", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Bayda", "Al Bayda", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Damar", "Dhamar", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Lahj", "Lahij", TBIJYemen$Province)

TBIJYemen <- TBIJYemen %>%
  mutate(TotalKilledMed = floor((TotalKilledMin + TotalKilledMax)/2)) %>%
  mutate(CiviliansKilledMed = floor((CiviliansKilledMin + CiviliansKilledMax)/2)) %>%
  mutate(MilitantsKilledMed = TotalKilledMed - CiviliansKilledMed) %>%
  filter(Date < as.Date("1/1/2016", "%m/%d/%Y") & Date > as.Date("1/1/2012", "%m/%d/%Y"))

#Leaders killed
NAFYemenLeaders <- read_csv("Data/Strikes Data/Tidy data/NAFYemenTidy.csv") %>%
  group_by(Date) %>%
  summarize(NumLeadersKilled = sum(NumLeadersKilled)) %>%
  transform(NumLeadersKilled = ifelse(Date == "2012-05-10", 2, 
                                      ifelse(Date == "2012-05-28", 1, 
                                             ifelse(Date == "2012-12-24", 1,
                                                    ifelse(Date == "2017-03-02", 1,
                                                           NumLeadersKilled))))) %>%
  mutate(LeaderKilled = ifelse(NumLeadersKilled > 0, 1, 0))
```

#### Graphs

```{r strike incidents by year}
strike_count_year <- TBIJYemen %>%
  mutate(year = year(Date)) %>%
  group_by(year) %>%
  summarize(count = n())

ggplot(strike_count_year, aes(year, count)) + 
  geom_line(linetype = 2) + 
  geom_point() + 
  scale_x_continuous(breaks = c(2002, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017)) + 
  ylim(0, 80) + 
  labs(title = "Reported number of covert strike incidents in Yemen, by year",
       x = "Year", y = "Number of incidents")
```

```{r strike location map}
yemen2 <- yemen

count_strikes <- TBIJYemen %>%
  group_by(Province) %>%
  summarize(count = n()) %>%
  rename(`NAME_1` = Province)

yemen2@data$id <- rownames(yemen2@data)
yemen2@data <- left_join(yemen2@data, count_strikes, by = "NAME_1")
yemen2_df <- fortify(yemen2)
yemen2_df <- left_join(yemen2_df, yemen2@data, by = "id")

ggplot() + 
  geom_polygon(data = yemen2_df, aes(x = long, y = lat, group = group, fill =
                                       count), color = "black", size = 0.25) +
  theme(aspect.ratio=.7) + 
  labs(title = "Location of covert strike incidents on AQAP and affiliates in Yemen, 2002 - 2017",
       fill = "Frequency") + 
  scale_fill_gradient(low='#FFFFCC', high='#006837') + 
  theme_opts
```

```{r fatalities per incident}
fatalities <- gtd_yemen %>%
  group_by(iyear) %>%
  summarize(NumAttacks = n(),
            Sum = sum(nkill, na.rm = TRUE), 
            Min = min(nkill, na.rm = TRUE), 
            Max = max(nkill, na.rm = TRUE), 
            Mean = mean(round(nkill,2), na.rm = TRUE),
            Median = median(nkill, na.rm = TRUE),
            Sd = sd(round(nkill,2), na.rm = TRUE))

strike_fatalities <- TBIJYemen %>%
  group_by(Date) %>%
  summarize(TotalMed = sum(TotalKilledMed),
            CiviliansMed = sum(CiviliansKilledMed),
            MilitantsMed = sum(MilitantsKilledMed)) %>% 
  gather(TotalMed, CiviliansMed, MilitantsMed, key = "type", value = "killed") %>%
  mutate(TypeLabel = ifelse(type == "TotalMed", "Total", ifelse(type == "CiviliansMed", "Civilians",
                                                                ifelse(type == "MilitantsMed", "Militants",
                                                                       NA))))

ggplot(strike_fatalities, aes(Date, killed)) + 
  geom_point(aes(color = TypeLabel)) + 
  geom_smooth(aes(color = TypeLabel)) + 
  labs(title = "Reported casualties from covert strike incidents",
       subtitle = "Average of maximum and minimum reported casualties",
       x = "Date", y = "Number killed per incident", color = "Casualty\nType")
  
```

```{r naf leaders killed}
year <- sort(rep(c(2002, seq(2009, 2017, 1)), 2))
LeaderKilled <- rep(c(0,1), 10)
decap <- data.frame(year, LeaderKilled)

decap_count <- NAFYemenLeaders %>%
  group_by(year(as.Date(Date, "%Y-%m-%d")), LeaderKilled) %>%
  summarize(freq = n())
colnames(decap_count) <- c("year", "LeaderKilled", "freq")

decap_count <- left_join(decap, decap_count, by = c("year", "LeaderKilled")) %>%
  transform(freq = ifelse(is.na(freq), 0, freq))

decap_count <- left_join(decap_count, strike_count_year, by = "year") %>%
  mutate(freq_weight = freq/count) %>%
  transform(LeaderKilled = as.factor(LeaderKilled))

ggplot(decap_count, aes(year, freq_weight)) + 
  geom_bar(aes(fill = LeaderKilled), stat = "identity") + 
  labs(title = "Percentage of strikes known to have killed at least one group leader",
       x = "Year", y = "Percentage of attacks",
       fill = "Killed leader?",
       caption = "Sources: The Bureau of Investigative Journalism,\nNew America Foundation") + 
  scale_y_continuous(labels = percent_format()) + 
  scale_x_continuous(breaks = c(2002, 2009, 2011, 2013, 2015, 2017)) + 
  scale_fill_manual(labels = c("No", "Yes"), values = c("black", "#999999"))
```

#### Table

```{r strike incidents table}
colnames <- c("Year", "# Incidents", "% Confirmed", "Avg. killed (min.)", "Avg. killed (max.)")
strikes <- c(strike_count_year$count, sum(strike_count_year$count))
confirmed_year <- TBIJYemen %>%
  mutate(year = year(Date)) %>%
  group_by(year, ConfirmedUSAttack) %>%
  summarize(freq = n())
confirmed_year <- left_join(confirmed_year, strike_count_year, by = "year") %>%
  mutate(freq_weight = round(freq/count*100,1)) %>%
  filter(ConfirmedUSAttack == "Confirmed")
confirmed <- c(confirmed_year$freq_weight, 
               round(sum(confirmed_year$freq)/sum(confirmed_year$count)*100,1))
  
strike_killed_year <- TBIJYemen %>%
  mutate(year = year(Date)) %>%
  group_by(year) %>%
  summarize(KilledMin = round(mean(TotalKilledMin),1), 
            KilledMax = round(mean(TotalKilledMax),1))

killedmin <- c(strike_killed_year$KilledMin, 
               round(mean(TBIJYemen$TotalKilledMin, na.rm = TRUE),1))
killedmax <- c(strike_killed_year$KilledMax,
               round(mean(TBIJYemen$TotalKilledMax, na.rm = TRUE),1))

strike_table <- data.frame(year, strikes, confirmed, killedmin, killedmax)
colnames(strike_table) <- colnames
xtable(strike_table)

```


## Regression analysis

```{r regression setup}
#attacks on same day treated as single attack

d <- 2/5
a <- 0.1

get_strike_casualties <- function(date, x) {
  obs <- filter(TBIJYemen, Date < date)
  obs <- group_by(obs, Date)
  obs <- summarize(obs, TotalKilledMed = sum(TotalKilledMed))
  leaders <- filter(NAFYemenLeaders, as.Date(Date, "%Y-%m-%d") < date)
  obs <- left_join(obs, leaders, by = "Date")
  obs <- transform(obs, NumLeadersKilled = ifelse(is.na(NumLeadersKilled), 0, NumLeadersKilled))
  obs <- mutate(obs, Diff = ceiling((date - Date)/30))
  obs <- filter(obs, Diff <= x)
  obs <- mutate(obs, TotKilledMedW = ((1 + a)^(NumLeadersKilled))*TotalKilledMed*d^(as.numeric(Diff) - 1))
  TotKilledMed <- sum(obs$TotKilledMedW)
  return(TotKilledMed)
}

# smoothed across last two months
TotKilledMedW2 <- map(gtd_yemen_casualties$date, function(i) get_strike_casualties(i, 2))
TotKilledMedW2 <- data.frame(TotKilledMedW2)
TotKilledMedW2 <- t(TotKilledMedW2)
TotKilledMedW2 <- data.frame(TotKilledMedW2)
rownames(TotKilledMedW2) <- NULL

# smoothed across last six months
TotKilledMedW6 <- map(gtd_yemen_casualties$date, function(i) get_strike_casualties(i, 7))
TotKilledMedW6 <- data.frame(TotKilledMedW6)
TotKilledMedW6 <- t(TotKilledMedW6)
TotKilledMedW6 <- data.frame(TotKilledMedW6)
rownames(TotKilledMedW6) <- NULL

# smoothed across last twelve months
TotKilledMedW12 <- map(gtd_yemen_casualties$date, function(i) get_strike_casualties(i, 13))
TotKilledMedW12 <- data.frame(TotKilledMedW12)
TotKilledMedW12 <- t(TotKilledMedW12)
TotKilledMedW12 <- data.frame(TotKilledMedW12)
rownames(TotKilledMedW12) <- NULL
```

```{r aggregate models}
#Model 1
yemen_lm_data <- bind_cols(gtd_yemen_casualties, TotKilledMedW2, TotKilledMedW6, TotKilledMedW12) %>%
  na.omit()

#smoothed across last two months
time_mod2 <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW2+1) + (log(TotKilledMedW2+1))^2, data = yemen_lm_data)

xtable(tidy(time_mod2))

#smoothed across last six months
time_mod6 <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW6+1) + (log(TotKilledMedW6+1))^2, data = yemen_lm_data)

xtable(tidy(time_mod6))

#smoothed across last twelve months
time_mod12 <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW12+1) + (log(TotKilledMedW12+1))^2, data = yemen_lm_data)

xtable(tidy(time_mod12))
```

```{r fixed effects models}
yemen_lm_fix_data <- yemen_lm_data %>%
  mutate(year = year(date))

#smoothed across last two months
time_mod2.fix <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW2+1) + (log(TotKilledMedW2+1))^2 + factor(year),
             data = yemen_lm_fix_data)


xtable(tidy(time_mod2.fix))

#smoothed across last six months
time_mod6.fix <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW6+1) + (log(TotKilledMedW6+1))^2 + factor(year),
             data = yemen_lm_fix_data)

summary(time_mod6.fix)
xtable(summary(time_mod6.fix))

#smoothed across last twelve months
time_mod12.fix <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW12+1) + (log(TotKilledMedW12+1))^2 + factor(year),
             data = yemen_lm_fix_data)

xtable(tidy(time_mod2))
summary(time_mod12.fix)
```

```{r pred plot}
yemen_lm_data_pred6 <- yemen_lm_data %>%
  add_predictions(time_mod6) 

ggplot(yemen_lm_data_pred6, aes(TotKilledMedW6, exp(pred)-1)) + 
  geom_line(color = "red") + 
  ylim(0,4.5) + 
  #scale_y_continuous(breaks = c(2, 3, 4), labels = c)
  labs(title = "Cumulative effect of covert strike fatalities vs. predicted interval between attacks",
       subtitle = "Smoothed measure of covert strike fatalities over six-month period",
       x = "Cumulative effect measure",
       y = "Predicted interval (days)")
```


```{r coef plot}
coefplot(time_mod6.fix,
         title = "Intervals between terrorist attacks ~ covert strike casualties\n(with fixed year effects)",
         newNames = c("log(TotKilledMedW6 + 1)" = "killed (logged)"),
         decreasing = TRUE)
```

