---
title: "TBIJYemen"
author: "Soo Wan Kim"
date: "May 1, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

library(tidyverse)
library(scales)
library(lubridate)
library(maptools)
library(raster)
library(rgdal)
library(broom)
library(modelr)
library(knitr)
library(xtable)
library(coefplot)

theme_set(theme_minimal())

#saved xlsx file as csv in Excel
gtd <- read_csv("Data/Terrorism Data/globalterrorismdb_0616dist.csv")

gtd_filt <- gtd %>%
  mutate(TargetType = ifelse(targtype1_txt %in% c("Military", "Police", "Terrorists/Non-State Militia"),
"Military", 
ifelse(targtype1_txt %in% c("Government (Diplomatic)", "Government (General)", "Violent Political Party"),
       "Government", "Other"))) %>%
  mutate(WeaponType = ifelse(weaptype1_txt %in% c("Biological", "Chemical", "Radiological",
                                                  "Fake Weapons", "Sabotage Equipment",
                                                         "Vehicle (not to include vehicle-borne explosives, i.e., car or truck bombs)", "Other", "Unknown"), "Unknown/Other",
                                    ifelse(weaptype1_txt == "Explosives/Bombs/Dynamite", 
                                           "Explosives", weaptype1_txt)))
```

# Yemen

```{r terrorist attack data}
#all attacks from 2009 on
gtd_yemen <- gtd_filt %>%
  filter(country_txt == "Yemen" & iyear >= 2009 & guncertain1 == 0 & gname %in% 
           c("Al-Qaida in the Arabian Peninsula (AQAP)", "Al-Qaida in Yemen")) %>%
  mutate(date = paste0(iyear,"-",imonth,"-",iday)) %>%
  transform(date = as.Date(date, "%Y-%m-%d")) %>%
  arrange(date)

#from March 2012 on
gtd_yemen2012 <- gtd_yemen %>%
  filter(date >= as.Date("3/1/2012", "%m/%d/%Y"))
```

## Suicide bombings only

```{r}
gtd_yemen2012_suibomb <- gtd_yemen2012 %>%
  filter(suicide == 1 & weaptype1_txt == "Explosives/Bombs/Dynamite")

gtd_yemen_casualties_suibomb <- gtd_yemen2012_suibomb %>%
  group_by(date) %>%
  summarize(attack_fatalities = sum(nkill))

date2 <- c(gtd_yemen_casualties_suibomb$date, NA)
date2 <- date2[-1]
gtd_yemen_casualties_suibomb$date2 <- as.Date(date2, "%Y-%m-%d")

gtd_yemen_casualties_suibomb <- gtd_yemen_casualties_suibomb %>%
  mutate(lull = date2 - date)
```

## Military targets only

```{r}
gtd_yemen2012_miltarg <- gtd_yemen2012 %>%
  filter(TargetType == "Military")

#all attacks from 2009 on
gtd_yemen_casualties_miltarg <- gtd_yemen2012_miltarg %>%
  group_by(date) %>%
  summarize(attack_fatalities = sum(nkill))

date2 <- c(gtd_yemen_casualties_miltarg$date, NA)
date2 <- date2[-1]
gtd_yemen_casualties_miltarg$date2 <- as.Date(date2, "%Y-%m-%d")

gtd_yemen_casualties_miltarg <- gtd_yemen_casualties_miltarg %>%
  mutate(lull = date2 - date)
```

### Covert strikes

```{r strike incident data}
#all strike incidents
TBIJYemen <- read_csv("Data/Strikes Data/Tidy data/TBIJYemenTidy.csv") %>%
  transform(Date = as.Date(Date, "%Y-%m-%d")) %>%
  transform(Province = ifelse(Province %in% c("Hadhramout", "Hadramout", "Hadaramout"), 
                              "Hadramawt", 
                              ifelse(Province %in% c("Across Yemen", "Southern Yemen", "Between Marib and Shabwa", "Shabwa/Hadramout", "Shabwa/Mareb border", "Jawf-Mareb border", "Bayda-Shabwa border", "Central Yemen", "-", "Marib/Al Jawf", "Across central Yemen", "Yemen", "Multiple provinces"), NA, Province)))
TBIJYemen$Province <- gsub("Sanaa", "San`a", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Shabwa", "Shabwah", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Saada", "Sa`dah", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Marib", "Ma'rib", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Mareb", "Ma'rib", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Jawf", "Al Jawf", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Bayda", "Al Bayda", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Damar", "Dhamar", TBIJYemen$Province)
TBIJYemen$Province <- gsub("Lahj", "Lahij", TBIJYemen$Province)

TBIJYemen <- TBIJYemen %>%
  mutate(TotalKilledMed = floor((TotalKilledMin + TotalKilledMax)/2)) %>%
  mutate(CiviliansKilledMed = floor((CiviliansKilledMin + CiviliansKilledMax)/2)) %>%
  mutate(MilitantsKilledMed = TotalKilledMed - CiviliansKilledMed) %>%
  filter(Date < as.Date("1/1/2016", "%m/%d/%Y"))

TBIJYemen2012 <- TBIJYemen %>%
  filter(Date >= as.Date("3/1/2012", "%m/%d/%Y"))
  
#Leaders killed
NAFYemenLeaders <- read_csv("Data/Strikes Data/Tidy data/NAFYemenTidy.csv") %>%
  group_by(Date) %>%
  summarize(NumLeadersKilled = sum(NumLeadersKilled)) %>%
  transform(NumLeadersKilled = ifelse(Date == "2012-05-10", 2, 
                                      ifelse(Date == "2012-05-28", 1, 
                                             ifelse(Date == "2012-12-24", 1,
                                                    ifelse(Date == "2017-03-02", 1,
                                                           NumLeadersKilled))))) %>%
  mutate(LeaderKilled = ifelse(NumLeadersKilled > 0, 1, 0))
```

## Regression analysis

```{r regression setup}
#attacks on same day treated as single attack
#again, do not filter strikes data by date!

d <- 3/5
a <- 0.1

get_strike_casualties <- function(date, x) {
  obs <- filter(TBIJYemen, Date < date)
  obs <- group_by(obs, Date)
  obs <- summarize(obs, TotalKilledMed = sum(TotalKilledMed))
  leaders <- filter(NAFYemenLeaders, as.Date(Date, "%Y-%m-%d") < date)
  obs <- left_join(obs, leaders, by = "Date")
  obs <- transform(obs, NumLeadersKilled = ifelse(is.na(NumLeadersKilled), 0, NumLeadersKilled))
  obs <- mutate(obs, Diff = floor((date - Date)/30))
  obs <- filter(obs, Diff <= x)
  obs <- mutate(obs, TotKilledMedW = ((1 + a)^(NumLeadersKilled))*TotalKilledMed*(1-d)^(as.numeric(Diff) - 1))
  TotKilledMed <- sum(obs$TotKilledMedW)
  return(TotKilledMed)
}
```

### Suicide bombings only

```{r suicide bombing reg totkill}
# smoothed across last two months, by p
TotKilledMedW2 <- map(gtd_yemen_casualties_suibomb$date, function(i) get_strike_casualties(i, 1))
TotKilledMedW2 <- data.frame(TotKilledMedW2)
TotKilledMedW2 <- t(TotKilledMedW2)
TotKilledMedW2 <- data.frame(TotKilledMedW2)
rownames(TotKilledMedW2) <- NULL

# smoothed across last six months
TotKilledMedW6 <- map(gtd_yemen_casualties_suibomb$date, function(i) get_strike_casualties(i, 6))
TotKilledMedW6 <- data.frame(TotKilledMedW6)
TotKilledMedW6 <- t(TotKilledMedW6)
TotKilledMedW6 <- data.frame(TotKilledMedW6)
rownames(TotKilledMedW6) <- NULL

# smoothed across last twelve months
TotKilledMedW12 <- map(gtd_yemen_casualties_suibomb$date, function(i) get_strike_casualties(i, 12))
TotKilledMedW12 <- data.frame(TotKilledMedW12)
TotKilledMedW12 <- t(TotKilledMedW12)
TotKilledMedW12 <- data.frame(TotKilledMedW12)
rownames(TotKilledMedW12) <- NULL
```

```{r aggregate models}
#Model 1
yemen_lm_data <- bind_cols(gtd_yemen_casualties_suibomb, TotKilledMedW2, TotKilledMedW6, TotKilledMedW12) %>%
  na.omit()

#smoothed across last two months
time_mod2 <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW2+1), data = yemen_lm_data)

summary(time_mod2)
#xtable(tidy(time_mod2))

#smoothed across last six months
time_mod6 <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW6+1), data = yemen_lm_data)

summary(time_mod6)
xtable(tidy(time_mod6))

#smoothed across last twelve months
time_mod12 <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW12+1), data = yemen_lm_data)

summary(time_mod12)
xtable(tidy(time_mod12))
```

```{r fixed effects models}
yemen_lm_fix_data <- yemen_lm_data %>%
  mutate(year = year(date))

#smoothed across last two months
time_mod2.fix <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW2+1) + factor(year),
             data = yemen_lm_fix_data)

summary(time_mod2.fix)
xtable(tidy(time_mod2.fix))

#smoothed across last six months
time_mod6.fix <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW6+1) + factor(year),
             data = yemen_lm_fix_data)

summary(time_mod6.fix)
xtable(summary(time_mod6.fix))

#smoothed across last twelve months
time_mod12.fix <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW12+1) + factor(year),
             data = yemen_lm_fix_data)

summary(time_mod12.fix)
xtable(tidy(time_mod2))
```

### Military targets only

```{r military target reg totkill}
# smoothed across last two months, by p
TotKilledMedW2 <- map(gtd_yemen_casualties_miltarg$date, function(i) get_strike_casualties(i, 1))
TotKilledMedW2 <- data.frame(TotKilledMedW2)
TotKilledMedW2 <- t(TotKilledMedW2)
TotKilledMedW2 <- data.frame(TotKilledMedW2)
rownames(TotKilledMedW2) <- NULL

# smoothed across last six months
TotKilledMedW6 <- map(gtd_yemen_casualties_miltarg$date, function(i) get_strike_casualties(i, 6))
TotKilledMedW6 <- data.frame(TotKilledMedW6)
TotKilledMedW6 <- t(TotKilledMedW6)
TotKilledMedW6 <- data.frame(TotKilledMedW6)
rownames(TotKilledMedW6) <- NULL

# smoothed across last twelve months
TotKilledMedW12 <- map(gtd_yemen_casualties_miltarg$date, function(i) get_strike_casualties(i, 12))
TotKilledMedW12 <- data.frame(TotKilledMedW12)
TotKilledMedW12 <- t(TotKilledMedW12)
TotKilledMedW12 <- data.frame(TotKilledMedW12)
rownames(TotKilledMedW12) <- NULL
```

```{r aggregate models}
#Model 1
yemen_lm_data <- bind_cols(gtd_yemen_casualties_miltarg, TotKilledMedW2, TotKilledMedW6, TotKilledMedW12) %>%
  na.omit()

#smoothed across last two months
time_mod2 <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW2+1), data = yemen_lm_data)

summary(time_mod2)
xtable(tidy(time_mod2))

#smoothed across last six months
time_mod6 <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW6+1), data = yemen_lm_data)

summary(time_mod6)
xtable(tidy(time_mod6))

#smoothed across last twelve months
time_mod12 <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW12+1), data = yemen_lm_data)

summary(time_mod12)
xtable(tidy(time_mod12))
```

```{r fixed effects models}
yemen_lm_fix_data <- yemen_lm_data %>%
  mutate(year = year(date))

#smoothed across last two months
time_mod2.fix <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW2+1) + factor(year),
             data = yemen_lm_fix_data)

summary(time_mod2.fix)
xtable(tidy(time_mod2.fix))

#smoothed across last six months
time_mod6.fix <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW6+1) + factor(year),
             data = yemen_lm_fix_data)

summary(time_mod6.fix)
xtable(summary(time_mod6.fix))

#smoothed across last twelve months
time_mod12.fix <- lm(log(as.numeric(lull)+1) ~ log(TotKilledMedW12+1) + factor(year),
             data = yemen_lm_fix_data)

summary(time_mod12.fix)
xtable(tidy(time_mod2))
```

```{r pred plot}
yemen_lm_data_pred6 <- yemen_lm_data %>%
  add_predictions(time_mod6) 

ggplot(yemen_lm_data_pred6, aes(TotKilledMedW6, exp(pred)-1)) + 
  geom_line(color = "red") + 
  #ylim(0,4.5) + 
  #scale_y_continuous(breaks = c(2, 3, 4), labels = c)
  labs(#title = "Predicted intervals without fixed effects",
       #subtitle = "Covert strike fatalities weighted across 6 months",
       x = "Cumulative effect measure",
       y = "Predicted interval (days)")
```


```{r coef plot}
coefplot(time_mod6.fix,
         title = "LM of log attack intervals with year fixed effects",
         newNames = c("log(TotKilledMedW6 + 1)" = "killed (logged)"),
         decreasing = TRUE)

coefplot(time_mod6.fix,
         title = NULL,
         newNames = c("log(TotKilledMedW6 + 1)" = "killed (logged)"),
         decreasing = TRUE)
```

